package com.aki.akiwarmup.random

import java.util.Locale
import kotlin.random.Random

// Dữ liệu Keyword Pool sạch (được làm mới toàn bộ hướng tới vai trò Nữ và không chứa vị trí cụ thể)
val keywordPool = mapOf(
    "emojis" to listOf(
        "👍", "😊", "🙏", "💪", "🔥", "💯", "😅", "👌", "🤝", "👀", "❤️",
        "✨", "🎉", "🌟", "🍀", "😃", "🥰", "😍", "🤩", "🤗", "🥳",
        "🌻", "🌸", "🎈", "🌞", "🌈", "🙌", "👏", "✌️", "⭐", "💝",
        "💖", "💘", "💗", "💓", "💛", "💚", "💙", "💜", "🧡", "☘️"
    )
)

// Các mẫu câu templates thiết kế chặt chẽ
val templates = setOf(
".",
    "16t nhận hk ạ",
    "16t nhận hk ạ vậy",
    "40t có nhạn kh e",
    "40t có nhận kh e nha c",
    "A ơi có nhận xâm hk hông",
    "A ơi làm ngồi hay đứng vậy ak ib e nha",
    "Ad nằm ở đâu ak ạ",
    "Ad tca bao nhiêu 1 tiếng z",
    "Ad tca đến mấy giờ z",
    "Ad ơi ko tăng ca đc ko nha",
    "Ad ơi làm ngồi hay đứng vậy ak vậy",
    "Bao nhiêu 1 ngày nha c",
    "Bn ơi bao nhiêu 1 ngày nha a",
    "Bn ơi chưa đủ 18t nhận ko nha c",
    "Bn ơi chỉ có cccd gốc đc ko nha a",
    "Bn ơi nằm ở đâu ak thế ạ",
    "Bạn ơi cccd photo đc ko nha c",
    "Bạn ơi còn nhận ko ạ đc ko ạ",
    "Bạn ơi làm ở đâu v hông",
    "Bạn ơi lương sao v bn oi đc ko ạ",
    "C ơi cty ở đâu z ak",
    "C ơi còn chỗ ko nha a",
    "C ơi còn nhận hồ sơ k vs",
    "C ơi cận có nhận ko ạ nha a",
    "C ơi ib đi z",
    "C ơi tư vấn e vs nha ad",
    "CT hay TV ạ",
    "CTY làm ngồi hay đứng vậy ak",
    "CTY ở đâu vậy",
    "Cj ơi 17t làm đc k ạ đc ko ạ",
    "Cj ơi check tin nhắn giúp em ib e nha",
    "Cj ơi cho e xin sđt liên hệ ko ạ",
    "Cj ơi chỉ có cccd gốc đc ko vậy",
    "Cj ơi cty ở đâu ạ",
    "Cj ơi còn tuyển dụng ko bạn ạ",
    "Cj ơi có hỗ trợ trọ ko ib e nha",
    "Cj ơi tư vấn e vs",
    "Cty co di ca đêm k ak",
    "Còn tuyển K cj",
    "Còn tuyển k ạ",
    "Còn tuyển nữ ko hông",
    "Cần bằng cấp ko đc ko ạ",
    "Ib cj ơi",
    "Làm ở đâu v",
    "Lương S z",
    "Mn ơi còn tuyển ko thế ạ",
    "Mn ơi còn tuyển nam ko ib e nha",
    "Mn ơi có hỗ trợ trọ ko hông",
    "Mn ơi lương cơ bản bao nhiêu ak",
    "Mn ơi địa điểm làm ở đâu nha c",
    "Mng ơi check zl tư vấn e nhé nha",
    "Mng ơi còn nhận ng ko ib e nha",
    "Mng ơi còn tiển kh e nhé",
    "Mng ơi còn tuyển nam ko nha a",
    "Mng ơi có bắt sản lượng hk ạ nha a",
    "Mng ơi có hỗ trợ trọ k hông",
    "Mng ơi có tc ko nhé",
    "Mng ơi lương sao v bn oi thế ạ",
    "O đâu z p",
    "P ơi còn tuyển nam ko nha c",
    "P ơi không tăng ca đc ko ko ạ",
    "P ơi ko tăng ca đc ko ak",
    "P ơi làm ngồi hay sao ạ z",
    "P ơi thiếu tuổi dc kh ak",
    "Sếp ơi check zl tư vấn e ạ",
    "Sếp ơi cty ở đâu z vậy",
    "Sếp ơi còn tuyển dụng ko bạn ak",
    "Sếp ơi có hỗ trợ trọ k ạ",
    "Sếp ơi có làm chủ nhật ko ak",
    "a ơi bao nhiêu 1 ngày vậy",
    "a ơi cccd photo ko công chứng đc ko ib e nha",
    "a ơi cccd photo ko công chứng đc ko nhé",
    "a ơi check zl tư vấn e nhé ib e nha",
    "a ơi check zl tư vấn e nhé nhé",
    "a ơi check zl tư vấn e nhé thế ạ",
    "a ơi cho e xin địa chỉ cty nhé",
    "a ơi cty ở đâu z nha",
    "a ơi cv nhẹ ko ạ z",
    "a ơi còn nhận k z",
    "a ơi còn nhận ko ạ ib e nha",
    "a ơi còn nhận việc k nha a",
    "a ơi còn nhận việc k ạ",
    "a ơi còn tiển kh e ib e nha",
    "a ơi có bao ăn ở ko nha",
    "a ơi có hỗ trợ trọ k ạ nha c",
    "a ơi có nhận xâm hk ib e nha",
    "a ơi có tăng ca ko thế ạ",
    "a ơi có đi ca đêm k ak hông",
    "a ơi có đi ca đêm k ak ko ạ",
    "a ơi có đi ca đêm k ak nha c",
    "a ơi cần hs gì ko ạ thế ạ",
    "a ơi cận có nhận ko ạ nha c",
    "a ơi inbox e nha nha c",
    "a ơi ko tăng ca đc ko",
    "a ơi làm gì v ib e nha",
    "a ơi làm ngày hay làm đêm v ạ",
    "a ơi làm đứng hay ngồi hông",
    "a ơi làm đứng hay ngồi vậy",
    "a ơi làm ở đâu v nha a",
    "a ơi lương sao v bn oi thế ạ",
    "a ơi lớn tuổi có nhận ko hông",
    "a ơi tomboy có nhận hk nha",
    "a ơi tuyển nam nữ kh vs",
    "a ơi tính lương sao vs",
    "a ơi địa điểm làm ở đâu ko ạ",
    "ad 16t nhận hk ạ vs",
    "ad check zl tư vấn e đc ko ạ",
    "ad check zl tư vấn e nhé vs",
    "ad cty ở đâu nha ad",
    "ad còn chỗ ko ak",
    "ad còn tiển kh e hông",
    "ad còn tuyển dụng ko bạn",
    "ad còn tuyển k ib e nha",
    "ad còn tuyển nữ ko ak",
    "ad có hỗ trợ tiền xăng ko ib e nha",
    "ad có phụ cấp gì k nha ad",
    "ad có tuyển vk ck ko e",
    "ad cần bằng cấp ko nha a",
    "ad hs cần công chứng ko đc ko ạ",
    "ad ib nhé",
    "ad inbox e nha ạ",
    "ad không tăng ca đc ko nha",
    "ad ko tăng ca đc ko",
    "ad làm ngày hay làm đêm v vậy",
    "ad làm ngồi hay đứng vậy ak ko ạ",
    "ad lương sao ko ạ",
    "ad tca đến mấy giờ nha ad",
    "ad ơi 16t nhận hk ạ vs",
    "ad ơi 40t có nhận kh e nha ad",
    "ad ơi 40t có nhận kh e nha c",
    "ad ơi cccd photo ko công chứng đc ko nhé",
    "ad ơi cho e hỏi còn nhận kh ak z",
    "ad ơi chưa có bằng cấp ba nhận ko nha ad",
    "ad ơi cty ở đâu v ak",
    "ad ơi cty ở đâu z",
    "ad ơi cty ở đâu z nha a",
    "ad ơi cv làm gì ạ ak",
    "ad ơi còn nhận hk",
    "ad ơi còn tuyển k ak",
    "ad ơi còn tuyển nam ko hông",
    "ad ơi có bao ăn ở ko",
    "ad ơi có bao ăn ở ko vậy",
    "ad ơi dễ làm kh ad ơi nhé",
    "ad ơi ib nha",
    "ad ơi làm hành chính hay đi ca vậy",
    "ad ơi làm j ạ đc ko ạ",
    "ad ơi làm ngày hay làm đêm v ko ạ",
    "ad ơi làm việc gì nha c",
    "ad ơi làm ở đâu v nha ad",
    "ad ơi làm ở đâu vậy vậy",
    "ad ơi lương cơ bản bao nhiêu hông",
    "ad ơi lương sao v bn oi đc ko ạ",
    "ad ơi lương thử việc s ib e nha",
    "ad ơi lớn tuổi có nhận ko nha",
    "ad ơi nào nhận vc nha a",
    "ad ơi tca bao nhiêu 1 tiếng nhé",
    "ad ơi tca đến mấy giờ nhé",
    "ad ơi tính lương sao nhé",
    "ad ơi xăm có nhận hok ak hông",
    "ad ơi ở đâu v ak ak",
    "bao nhieu 1 ngày",
    "bao nhiêu 1 ngày thế ạ",
    "bn ơi 16t nhận hk ạ nha c",
    "bn ơi check zl tư vấn e nhé vậy",
    "bn ơi cho e hỏi còn nhận kh ak z",
    "bn ơi chưa có bằng cấp ba nhận ko nha",
    "bn ơi chưa có bằng cấp ba nhận ko nha c",
    "bn ơi chưa có bằng cấp ba nhận ko nhé",
    "bn ơi chưa đủ 18t nhận ko nhé",
    "bn ơi còn chỗ ko hông",
    "bn ơi còn tuyển dụng ko bạn vậy",
    "bn ơi còn tuyển k ak",
    "bn ơi có bao ăn ở ko ạ",
    "bn ơi có nhận xâm hk hông",
    "bn ơi có tuyển vk ck ko e nha",
    "bn ơi cần hs gì ko ạ",
    "bn ơi cận có nhận ko ạ ạ",
    "bn ơi hs cần công chứng ko nha",
    "bn ơi lương ntn vậy vậy",
    "bn ơi lương thực lãnh bao nhiêu ak",
    "bn ơi tca đến mấy giờ nha ad",
    "bn ơi tca đến mấy giờ đc ko ạ",
    "bn ơi tomboy có nhận hk đc ko ạ",
    "bn ơi tính lương sao nha a",
    "bn ơi xăm mình có nhận ko",
    "bn ơi xăm mình có nhận ko nha c",
    "bn ơi xăm mình có nhận ko z",
    "bn ơi đường số mấy ak",
    "bạn ơi cccd photo ko công chứng đc ko nhé",
    "bạn ơi chỉ có cccd gốc đc ko vs",
    "bạn ơi cv nhẹ ko ạ thế ạ",
    "bạn ơi còn nhận ko ạ đc ko ạ",
    "bạn ơi còn nhận ng ko ak",
    "bạn ơi còn nhận ng ko nha c",
    "bạn ơi còn tiển kh e thế ạ",
    "bạn ơi còn tuyển nam ko ạ",
    "bạn ơi còn tuyển nữ ko",
    "bạn ơi có hỗ trợ trọ k ạ",
    "bạn ơi có làm chủ nhật ko",
    "bạn ơi có tăng ca ko",
    "bạn ơi ib đi ạ",
    "bạn ơi inbox e nha hông",
    "bạn ơi làm đứng hay ngồi nhé",
    "bạn ơi làm ở đâu v thế ạ",
    "bạn ơi làm ở đâu vậy thế ạ",
    "bạn ơi lương cơ bản bao nhiêu ak",
    "bạn ơi lương ntn vậy ko ạ",
    "bạn ơi lương sao vậy",
    "bạn ơi lương thử việc s ib e nha",
    "bạn ơi lương thực lãnh bao nhiêu thế ạ",
    "bạn ơi lớn tuổi có nhận ko ak",
    "bạn ơi tomboy có nhận hk nha ad",
    "bạn ơi tomboy có nhận hk vậy",
    "bạn ơi tomboy có nhận hk z",
    "bạn ơi tuyển nam nữ kh ko ạ",
    "bạn ơi tính lương sao ak",
    "bạn ơi tính lương sao z",
    "bạn ơi đường số mấy nhé",
    "c ơi 17t làm đc k ạ ib e nha",
    "c ơi cccd photo đc ko nha",
    "c ơi cccd photo đc ko vậy",
    "c ơi check tin nhắn giúp em nha a",
    "c ơi chưa đủ 18t nhận ko nhé",
    "c ơi cty ở đâu z nhé",
    "c ơi cv nhẹ ko ạ nha a",
    "c ơi còn nhận ko ạ ak",
    "c ơi còn nhận việc k ko ạ",
    "c ơi còn tuyển ko z",
    "c ơi còn tuyển nam ko đc ko ạ",
    "c ơi còn tuyển nữ ko ko ạ",
    "c ơi có bao ăn ở ko ko ạ",
    "c ơi có bắt sản lượng hk ạ z",
    "c ơi có phòng trọ ko nha ad",
    "c ơi có phụ cấp gì k vs",
    "c ơi có đi ca đêm k ak nha a",
    "c ơi công việc cụ thể là gì đc ko ạ",
    "c ơi hs cần công chứng ko nha a",
    "c ơi ib đi đc ko ạ",
    "c ơi ko tăng ca đc ko vậy",
    "c ơi ko tăng ca đc ko đc ko ạ",
    "c ơi làm hành chính hay đi ca hông",
    "c ơi làm ngày hay làm đêm v nhé",
    "c ơi làm ngày mấy tiếng ib e nha",
    "c ơi làm ở đâu v vậy",
    "c ơi làm ở đâu vậy ko ạ",
    "c ơi lương sao",
    "c ơi lương sao v bn oi nha c",
    "c ơi lớn tuổi có nhận ko ạ",
    "c ơi tca hay xoay ca vậy em nha ad",
    "c ơi xăm có nhận hok ak đc ko ạ",
    "c ơi ở đâu v ak nha c",
    "c ơi, còn nhận ng ko",
    "cccd photo ko công chứng đc ko ko ạ",
    "cccd photo ko công chứng đc ko nha ad",
    "cccd photo đc ko",
    "check zl tư vấn e nhé",
    "cho cj 1 chân vơi nha",
    "cho e hỏi còn nhạn kh ak",
    "cho e xin sđt liên hệ đc ko ạ",
    "cho e xin địa chỉ CTY với",
    "cho xin 1 chân vs",
    "chưa đủ 18t nhận ko nha a",
    "cj ơi bao nhiêu 1 ngày nha c",
    "cj ơi cccd photo đc ko z",
    "cj ơi check zl tư vấn e thế ạ",
    "cj ơi cho e hỏi còn nhận kh ak đc ko ạ",
    "cj ơi cho e xin địa chỉ cty vs",
    "cj ơi chưa đủ 18t nhận ko vs",
    "cj ơi cty ở đâu z nha",
    "cj ơi cv làm gì ạ nhé",
    "cj ơi còn slot nào ko ko ạ",
    "cj ơi còn tuyển nam ko",
    "cj ơi còn tuyển nữ ko nha ad",
    "cj ơi có hỗ trợ trọ k ạ ạ",
    "cj ơi có phòng trọ ko nha ad",
    "cj ơi công việc cụ thể là gì z",
    "cj ơi cần bằng cấp ko nhé",
    "cj ơi ib ko ạ",
    "cj ơi ib nha",
    "cj ơi inbox e nha ạ",
    "cj ơi làm ngày mấy tiếng ib e nha",
    "cj ơi làm ngày mấy tiếng thế ạ",
    "cj ơi làm ngồi hay đứng vậy ak hông",
    "cj ơi làm ở đâu vậy ko ạ",
    "cj ơi lắp ráp hay đóng gói ko ạ",
    "cj ơi nào nhận vc",
    "cj ơi nào nhận vc ạ",
    "cj ơi thời vụ 8 tiếng bao nhiêu vậy vs",
    "cj ơi tomboy có nhận hk ak",
    "cj ơi tính lương sao hông",
    "cj ơi vào làm gì vậy vs",
    "cj ơi đường số mấy hông",
    "cj ơi địa điểm làm ở đâu nha c",
    "con tuyen k bn",
    "cty còn k c",
    "cty cũ em làm nè",
    "cty gì đó",
    "cty lm về gì ạ",
    "cty làm gì ạ",
    "cty nằm đâu",
    "cty nằm đâu nha a",
    "cty nằm đâu đc ko ạ",
    "cty ở đâu nha ad",
    "cty ở đâu nha c",
    "cty ở đâu v nha ad",
    "cty ở đâu z thế ạ",
    "cty ở đâu đc ko ạ",
    "cung ty o dau day ạ",
    "cv nhẹ ko ạ",
    "còn hk ạ",
    "còn k",
    "còn k ạ",
    "còn nhan tv kh c",
    "còn nhận hk",
    "còn nhận ko ạ",
    "còn nhận ng ko",
    "còn tiển kh e",
    "còn tuyẻn kg",
    "còn tuyển dụng ko bạn",
    "còn tuyển không",
    "còn tuyển không z",
    "còn tuyển ko nha c",
    "có bắt sản lượng hk ạ",
    "có chạy sản lượng ko",
    "có cần hs gì ko ạ",
    "có hỗ trợ trọ k",
    "có hỗ trợ trọ k ạ",
    "có làm chủ nhật ko",
    "có nhận bà bầu ko ạ",
    "có nhận chính thức k",
    "có nhận ct hk c",
    "có nhận làm thời vụ ko ạ",
    "có nhận tv k",
    "có nhận xâm hk",
    "có nhận xăm hk",
    "có tc ko",
    "có tc ko nha",
    "có thưởng gì k",
    "có tiển vk ck ko e",
    "có tuyển chính thức ko",
    "có đi hành chính ko",
    "cần bằng cấp ko ko ạ",
    "cận có nhận ko ạ",
    "dễ làm kh ad ơi",
    "dễ làm kh ad ơi z",
    "e 17t làm đc k ạ sắp 18",
    "em mang dép đc hk",
    "hành chính hay đi ca ạ",
    "ib",
    "ib cj ơi nha",
    "ib đi",
    "không tăng ca đc ko",
    "ko tăng ca đc ko",
    "ko tăng ca đc ko z",
    "lm từ mấy giờ",
    "luong s",
    "luong sao ak",
    "lv từ mấy h",
    "làm dễ ko",
    "làm gì v nhé",
    "làm hành chính hay đi ca vậy . Vô ca mấy giờ",
    "làm ngày hay làm đêm v",
    "làm ngồi hay sao ạ",
    "làm ngồi hay sao ạ ak",
    "làm tca đến mấy gì em",
    "làm tv rồi lên ct đc ko",
    "làm việc gì",
    "làm đứng hay ngồi nha",
    "làm ở đâu vậy",
    "lương ntn vậy",
    "lương s",
    "lương sao nhé",
    "lương sao v bn oi",
    "lương sao vậy ạ",
    "lắp ráp hay đóng gói ạ",
    "mn ơi 17t làm đc k ạ nha",
    "mn ơi cccd photo đc ko z",
    "mn ơi check tin nhắn giúp em thế ạ",
    "mn ơi chưa có bằng cấp ba nhận ko ko ạ",
    "mn ơi chỉ có cccd gốc đc ko hông",
    "mn ơi cty ở đâu thế ạ",
    "mn ơi cty ở đâu đc ko ạ",
    "mn ơi còn nhận hk nha c",
    "mn ơi còn nhận k nha a",
    "mn ơi còn nhận việc k vậy",
    "mn ơi còn tuyển k nha ad",
    "mn ơi còn tuyển nam ko thế ạ",
    "mn ơi có bao ăn ở ko nha",
    "mn ơi có nhận xâm hk nha ad",
    "mn ơi dễ làm kh ad ơi đc ko ạ",
    "mn ơi hs cần công chứng ko nha",
    "mn ơi ib cj ơi vs",
    "mn ơi inbox e nha nha ad",
    "mn ơi không tăng ca đc ko ko ạ",
    "mn ơi ko tăng ca đc ko nha c",
    "mn ơi lương sao nha a",
    "mn ơi lớn tuổi có nhận ko ak",
    "mn ơi tuyển nam nữ kh nha a",
    "mn ơi tính lương sao nha",
    "mn ơi tư vấn e với ạ ạ",
    "mn ơi xin địa chỉ cty",
    "mn ơi xin địa chỉ cty đc ko ạ",
    "mn ơi đường số mấy hông",
    "mn ơi ở đâu v ak vs",
    "mng ơi check zl tư vấn e nhé",
    "mng ơi cho e xin địa chỉ cty vs z",
    "mng ơi chưa có bằng cấp ba nhận ko ak",
    "mng ơi cty nằm đâu ạ",
    "mng ơi cty ở đâu z",
    "mng ơi cv làm gì ạ thế ạ",
    "mng ơi còn nhận hồ sơ k ạ",
    "mng ơi còn nhận việc k nhé",
    "mng ơi còn tuyển nam ko đc ko ạ",
    "mng ơi có tuyển vk ck ko e nha c",
    "mng ơi cần bằng cấp ko thế ạ",
    "mng ơi làm hành chính hay đi ca nha ad",
    "mng ơi làm ngồi hay sao ạ nhé",
    "mng ơi lương cơ bản bao nhiêu z",
    "mng ơi lương sao",
    "mng ơi tca hay xoay ca vậy em đc ko ạ",
    "mng ơi tính lương sao nha ad",
    "mng ơi tư vấn e với ạ nha ad",
    "mng ơi xin địa chỉ cty ak",
    "mng ơi xin địa chỉ cty vs",
    "mng ơi đường số mấy ạ",
    "mng ơi địa điểm làm ở đâu hông",
    "mng ơi ở đâu v ak vs",
    "nhạn đến bn tuổi v",
    "nhận thiếu tủi ko ạ",
    "nào nhận vc",
    "nào nhận vc ak",
    "nào nhận vc nhé",
    "này 9thức hay tvụ",
    "nằm ở đâu ak",
    "p ơi 40t có nhận kh e nha a",
    "p ơi bà bầu có nhận ko ạ nhé",
    "p ơi check tin nhắn giúp em ko ạ",
    "p ơi cho e xin địa chỉ cty vs ib e nha",
    "p ơi cho e xin địa chỉ cty đc ko ạ",
    "p ơi chưa có bằng cấp ba nhận ko ib e nha",
    "p ơi chưa đủ 18t nhận ko nha",
    "p ơi còn chỗ ko hông",
    "p ơi còn nhận hồ sơ k ak",
    "p ơi còn slot nào ko ak",
    "p ơi còn tiển kh e nha c",
    "p ơi có làm chủ nhật ko nhé",
    "p ơi có tuyển vk ck ko e nhé",
    "p ơi cần bằng cấp ko nha",
    "p ơi cần hs gì ko ạ vs",
    "p ơi ib",
    "p ơi ib cj ơi nhé",
    "p ơi inbox e nha ak",
    "p ơi không tăng ca đc ko ko ạ",
    "p ơi không tăng ca đc ko vs",
    "p ơi làm gì v nha",
    "p ơi làm ngày mấy tiếng nha a",
    "p ơi làm đứng hay ngồi nha a",
    "p ơi lương thử việc s",
    "p ơi tca hay xoay ca vậy em",
    "p ơi tca hay xoay ca vậy em đc ko ạ",
    "p ơi thiếu tuổi dc kh vs",
    "p ơi tính lương sao ib e nha",
    "p ơi tính lương sao thế ạ",
    "p ơi tư vấn e vs thế ạ",
    "p ơi vào làm gì vậy nha ad",
    "p ơi xin địa chỉ cty nha",
    "rep cmt cái sếp ơi",
    "sếp ơi chỉ có cccd gốc đc ko nha c",
    "sếp ơi cty nằm đâu nhé",
    "sếp ơi cty ở đâu z",
    "sếp ơi cv làm gì ạ thế ạ",
    "sếp ơi còn nhận hk",
    "sếp ơi còn nhận k đc ko ạ",
    "sếp ơi còn nhận ng ko vs",
    "sếp ơi có hỗ trợ tiền xăng ko ak",
    "sếp ơi có hỗ trợ trọ k ạ vậy",
    "sếp ơi có nhận xăm hk ko ạ",
    "sếp ơi có tc ko thế ạ",
    "sếp ơi cần bằng cấp ko ko ạ",
    "sếp ơi cận có nhận ko ạ nha ad",
    "sếp ơi cận có nhận ko ạ thế ạ",
    "sếp ơi ko tăng ca đc ko nha",
    "sếp ơi làm ngày mấy tiếng",
    "sếp ơi làm ngồi hay sao ạ nhé",
    "sếp ơi lương cơ bản bao nhiêu ko ạ",
    "sếp ơi lương ntn vậy",
    "sếp ơi lương sao vs",
    "sếp ơi lắp ráp hay đóng gói nha",
    "sếp ơi lắp ráp hay đóng gói nha c",
    "sếp ơi tca bao nhiêu 1 tiếng đc ko ạ",
    "sếp ơi tca đến mấy giờ thế ạ",
    "sếp ơi tomboy có nhận hk vậy",
    "sếp ơi tính lương sao ak",
    "sếp ơi tư vấn e với ạ hông",
    "sếp ơi vào làm gì vậy",
    "sếp ơi xăm có nhận hok ak ko ạ",
    "sếp ơi ở đâu v ak ko ạ",
    "tca bao nhiêu 1 tiếng",
    "tca bao nhiêu 1 tiếng ib e nha",
    "tca hay xoay ca vậy em",
    "tca đến mấy giờ",
    "thiếu tháng có nhận ko chị",
    "thiếu tuổi dc kh",
    "thời vụ 8 tiếng bao nhiêu vậy",
    "tomboy có nhận hk",
    "tu vấn với ạ",
    "tuan hay thang vậy",
    "tuyển lại rồi hả",
    "tuyển nam nữ kh",
    "tv em với",
    "xin sdt",
    "xăm có nhạn hok ak",
    "đường số mấy",
    "đường số mấy hông",
    "địa điểm làm ở đâu ak",
    "địa điểm làm ở đâu nha a",
    "ở chỗ nào",
    "ở đâu",
    "ở đâu v ak",
)

// Từ điển các lỗi sai phổ biến
val exactTypos = mapOf(
    "việc" to listOf("ziệc", "viêc"),
    "chỗ" to listOf("chổ"),
    "nghỉ" to listOf("nghĩ"),
    "nghĩ" to listOf("ngĩ"),
    "tuổi" to listOf("tủi", "tuỗi"),
    "tuyển" to listOf("tuyễn"),
    "lương" to listOf("lươg"),
    "kinh" to listOf("kih"),
    "nghiệm" to listOf("ngiệm"),
    "hồ" to listOf("hô"),
    "sơ" to listOf("sờ"),
    "tháng" to listOf("thág"),
    "gì" to listOf("j", "zì"),
    "thì" to listOf("thỳ"),
    "quá" to listOf("wá", "qá"),
    "được" to listOf("đươc", "dc", "đc"),
    "làm" to listOf("lm", "lam"),
    "cũ" to listOf("củ"),
    "kỹ" to listOf("kỉ", "kĩ"),
    "sao" to listOf("s"),
    "rồi" to listOf("rùi", "dồi", "r", "ròi"),
    "dạ" to listOf("zạ")
)

// Các quy tắc thay thế chữ cái (dùng Regex)
val typoRules = listOf(
    Regex("t$") to "c",
    Regex("c$") to "t",
    Regex("n$") to "ng",
    Regex("ng$") to "n",
    Regex("^l") to "n",
    Regex("ả") to "ã", Regex("ã") to "ả",
    Regex("ẻ") to "ẽ", Regex("ẽ") to "ẻ",
    Regex("ỉ") to "ĩ", Regex("ĩ") to "ỉ",
    Regex("ỏ") to "õ", Regex("õ") to "ỏ",
    Regex("ủ") to "ũ", Regex("ũ") to "ủ"
)

// Hàm tạo lỗi chính tả tự nhiên
fun applyTypos(text: String, isTypoEnabled: Boolean): String {
    if (!isTypoEnabled) return text

    // Tỉ lệ câu có lỗi chính tả là 30%
    if (Random.nextDouble() > 0.30) return text

    val words = text.split(" ").toMutableList()
    if (words.isEmpty()) return text

    // Chọn ngẫu nhiên tối đa 1 hoặc 2 vị trí từ để tạo lỗi
    val typoCount = if (words.size > 5) Random.nextInt(1, 3) else 1
    val indicesToModify = words.indices.shuffled().take(typoCount)

    for (index in indicesToModify) {
        val word = words[index]
        val isFirstCharUpper = word.isNotEmpty() && word[0].isUpperCase()

        // Tách dấu câu ra khỏi từ
        val matchResult = Regex("^([a-zA-ZÀ-ỹ]+)([.,!?]*)$").find(word)

        if (matchResult != null) {
            val pureWord = matchResult.groupValues[1].lowercase()
            val punctuation = matchResult.groupValues[2]
            var newWord = pureWord

            // Kiểm tra trong từ điển lỗi kinh điển
            if (exactTypos.containsKey(pureWord)) {
                newWord = exactTypos[pureWord]!!.random()
            } else {
                // Áp dụng quy tắc Regex
                val applicableRules = typoRules.filter { it.first.containsMatchIn(pureWord) }
                if (applicableRules.isNotEmpty()) {
                    val rule = applicableRules.random()
                    newWord = pureWord.replace(rule.first, rule.second)
                }
            }

            // Khôi phục viết hoa và dấu câu
            if (isFirstCharUpper) {
                newWord = newWord.replaceFirstChar {
                    if (it.isLowerCase()) it.titlecase(Locale.getDefault()) else it.toString()
                }
            }
            words[index] = newWord + punctuation
        }
    }
    return words.joinToString(" ")
}

// Hàm tạo bình luận
fun generateComment(enableTypos: Boolean = true): String {
    var template = templates.shuffled().random()

    if (Random.nextDouble() < 0.10) {
        template += " {emojis}"
    }

    // Sử dụng Regex để tìm các Placeholder {tên_biến} và thay thế
    val regex = Regex("\\{(\\w+)\\}")
    template = regex.replace(template) { matchResult ->
        val key = matchResult.groupValues[1]
        val pool = keywordPool[key]
        if (!pool.isNullOrEmpty()) {
            pool.random()
        } else {
            matchResult.value // Giữ nguyên {tên_biến} nếu không có dữ liệu
        }
    }

    // Tự động chuẩn hóa dấu câu ở cuối câu hỏi
    val isQuestion = template.contains("không") || template.contains("chưa") ||
            template.contains("nào") || template.contains("bao nhiêu") ||
            template.contains("sao") || template.contains("thế nào")

    if (isQuestion && !template.endsWith("?") && !template.endsWith(".") && !template.endsWith("!")) {
        // Tỷ lệ thêm dấu chấm hỏi là 80% đối với câu hỏi
        if (Random.nextDouble() < 0.80) {
            template += "?"
        }
    }

    // Giả lập viết thường toàn bộ (40% cơ hội)
    template = if (Random.nextDouble() < 0.40) {
        template.lowercase()
    } else {
        // Viết hoa chữ cái đầu tiên của câu
        if (template.isNotEmpty()) {
            template.replaceFirstChar {
                if (it.isLowerCase()) it.titlecase(Locale.getDefault()) else it.toString()
            }
        } else template
    }

    return applyTypos(template, enableTypos)
}